### ISSUE TITLE
I ran into some problems when running the experiment

### ISSUE THREAD

**Issue by YefanWu** [anonymousheliks23/heliks#1]
I want to re-evaluate your experiments and build it for further development. I cloned the project and ran the docker container in Ubuntu 22.04. When I use ./seal_mm_tests.sh and ./seal_cv_tests.sh, the terminal outputs information as follows,

./seal_mm_tests.sh: 3: docker-compose: not found
./seal_mm_tests.sh: 5: docker-compose: not found
./seal_mm_tests.sh: 7: docker-compose: not found
...

I will appreciate very much if u can help find the problem. I am a newb about the docker and I don't understand how the system works at all.

**Comment by shashankballa** [comment]
I updated the build instructions in the readme. You should first clone the repository, enter the `HELiKs` root directory and open a shell terminal at the root directory. All the commands in the build instructions must be run in this terminal.

**Comment by YefanWu** [comment]
> I updated the build instructions in the readme. You should first clone the repository, enter the `HELiKs` root directory and open a shell terminal at the root directory. All the commands in the build instructions must be run in this terminal.

I fixed this problem by installing missing docker-compose. Thanks you for replying. Have a nice day!
